hash-format = "sha256"

[[files]]
file = "mods/betterf3.pw.toml"
hash = "43a3ae3e208a09927e59b283bbcddb696f42bca7ad065a161926289641f62cbc"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
hash = "4e596f70957b214851ee57422d421ec59037425f5b209fc5813d44918d91c1b9"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "27f9b131c5f2db3267fe07cab7c104a5651cbdfbdc1f023374fe6d93f686f26b"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "d80ddf72ebc03bb698043968c2b06272fbbbcf45927e67083d19e65f322b1ca9"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "144c9b2dd530cfdf13dd3757c8eddcf6cfcc9631536dcabdd1378a39c8bdf47b"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c2597298dd5d160ca9161a12bcb5e933118cb66718b27c0945938eedb19dd90d"
metafile = true

[[files]]
file = "mods/libzoomer.pw.toml"
hash = "0bdc8675762015dd0dc3a72420f0bd60a072c456a0d1ae115c4bb0c5614f1c12"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "8d8efd1b0fdd39724444d3f38573077f82b9f7091376d1c18a52404d7053626c"
metafile = true

[[files]]
file = "mods/midnightcontrols.pw.toml"
hash = "f1438cc7d963b2603fb58f1b19e43d5fcaf745f03a4c07fb394529e1400570bf"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
hash = "d157b9199d778da79cc8a08a57b4ba998cea1a57b75c54ca5b3a9892a05996ce"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "d3716e8b83ff2044733b4e58ea266cb3f2957f472d08d015abe6a54e425202e4"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "6c8c93e74e46a0cac65179d027e9aac4eaebc44847604b0ff86644f3030116e8"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "b6c8fe81a75bc2c3292ef642e62985c2d9e270ad26f7aa044ff33b906425e8a8"
metafile = true

[[files]]
file = "mods/ok-zoomer.pw.toml"
hash = "839bf2a1076a44c572c46c402ef5603d28e772cb5e791011c3c04d94656e48d5"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0b1a53f585b616faa04cb2bccdb05e67c0fbc1887b209c191d4fb7c91d13cac4"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "00f143ea655549e902548575aff0fbffee69802bfe76a73b35187b05c690af07"
metafile = true
